apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Injects network packet corruption on pods belonging to an app deployment
kind: ChaosExperiment
metadata:
  name: pod-network-corruption
  version: 0.1.0
spec:
  definition:
    permissions:
      apiGroups:
        - ""
        - "extensions"
        - "apps"
        - "batch"
        - "litmuschaos.io"
      resources:
        - "daemonsets"
        - "statefulsets"
        - "deployments"
        - "jobs"
        - "pods"
        - "pods/exec"
        - "chaosengines"
        - "chaosexperiments"
        - "chaosresults"
      verbs:
        - "*"
    image: "litmuschaos/ansible-runner:ci"
    args:
    - -c
    - ansible-playbook ./experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml -i /etc/ansible/hosts -vv; exit 0
    command:
    - /bin/bash
    env:
    - name: ANSIBLE_STDOUT_CALLBACK
      value: 'default'

    - name: TARGET_CONTAINER
      value: ''

     # provide lib image
    - name: LIB_IMAGE
      value: 'gaiaadm/pumba:0.6.5' 

    - name: NETWORK_INTERFACE
      value: 'eth0'

    - name: NETWORK_PACKET_CORRUPTION_PERCENTAGE
      value: '100' #in PERCENTAGE

    - name: TOTAL_CHAOS_DURATION
      value: '60000' #in ms

    - name: LIB
      value: 'pumba'
    labels:
      name: pod-network-corruption
