apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-network-corruption
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: CNCF
    repository: https://github.com/litmuschaos/chaos-charts
    support: https://slack.kubernetes.io/
spec:
  displayName: pod-network-corruption
  categoryDescription: |
    Pod-network-corruption contains chaos to corrupt network packets being sent from kubernetes pods. Experiments can inject percentage packet corruption on the app replica pods. 
    - Causes corrupted packets being sent and tests the applications' handling of these using pumba.
    - The application pod should be healthy once chaos is stopped. Service-requests should be served (say, via alternate replicas) despite chaos.
  keywords:
    - Kubernetes
    - Network
  platforms:
    - GKE
    - OpenShift
    - minikube
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
  icon:
    - base64data: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/pod-network-corruption/experiment.yaml 
